"""Add rating and other fields to LectureReview

Revision ID: 13423bdbf3bc
Revises: 
Create Date: 2025-10-29 00:57:23.003627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13423bdbf3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('homework', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('team_project', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grading', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('attendance', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('exam_count', sa.String(length=20), nullable=True))
        batch_op.alter_column('semester',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture_review', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('exam_count')
        batch_op.drop_column('attendance')
        batch_op.drop_column('grading')
        batch_op.drop_column('team_project')
        batch_op.drop_column('homework')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
